### ISSUE TITLE
SPIFlashDisk_Demo not working

### ISSUE THREAD

**Issue by madias123** [huaweiwx/STM32GENERIC#5]
/xxxx/USBMassStorage/examples/SpiFlashDisk_Demo/SpiFlashDisk_Demo.ino: In function 'void setup()':
SpiFlashDisk_Demo:22: error: expected unqualified-id before '.' token
   SPIFLASH.begin(); //need while usb unconnected

It seems that SPIFLASH isn't defined?

**Comment by huaweiwx** [comment]
This is an early example，The  class name and predefine a instance whose name was changed to arduino-style spiFlash.
please change   SPIFLASH  to  spiFlash.
thanks!

**Comment by madias123** [comment]
Thank you, for your prompt reply/fix!
