### ISSUE TITLE
fatal error: stm32_HAL/stm32XXxx_ll_adc.h

### ISSUE THREAD

**Issue by VictorTagayun** [huaweiwx/STM32GENERIC#6]
In file included from D:\Hobby\Arduino\arduino-1.8.7\hardware\STM32GENERIC\STM32\cores\arduino/stm32/stm32_gpio.h:686:0,

                 from D:\Hobby\Arduino\arduino-1.8.7\hardware\STM32GENERIC\STM32\cores\arduino/Arduino.h:183,

                 from sketch\Blink.ino.cpp:1:

D:\Hobby\Arduino\arduino-1.8.7\hardware\STM32GENERIC\STM32\cores\arduino/stm32/stm32_ADC.h:27:42: fatal error: stm32_HAL/stm32XXxx_ll_adc.h: No such file or directory

 #  include "stm32_HAL/stm32XXxx_ll_adc.h"

                                          ^

compilation terminated.

exit status 1
Error compiling for board Discovery F429ZI(180M).

**Comment by huaweiwx** [comment]
This file has been added.
Thanks!
